# Generated by Django 5.0.4 on 2024-04-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_of_entry', models.CharField(choices=[('RECEIPT', 'Receipt'), ('PAYMENT', 'Payment')], default='None', max_length=100)),
                ('particulars', models.TextField(max_length=200)),
                ('detail', models.TextField(max_length=200)),
                ('amount', models.IntegerField()),
                ('cash', models.IntegerField()),
            ],
        ),
    ]
